[build]
  publish = "."

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/player/:id"
  to   = "/player.html?id=:id"
  status = 200

[[redirects]]
  from = "/rank"
  to   = "/rank.html"
  status = 200
